---
- name: Install base tools
  become: True
  apt:
    pkg:
      - xorg
      - xdotool
      - htop
      - feh
      - nload
      - lightdm
      - ufw
      - git
      - graphicsmagick-imagemagick-compat
    state: present
    update_cache: yes

- name: Disallow SSH with pwd
  become: True
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication.*"
    line: "PasswordAuthentication no"
    state: "present"
    insertbefore: EOF
  notify:
   - Restart ssh

- name: Enable ssh on startup
  become: True
  systemd:
    name: "ssh"
    enabled: True

- name: Add pixelflut user
  become: True
  user:
    name: "{{ pixelflut_user }}"
    create_home: yes
    home: "{{ pixelflut_user_home }}"
    append: yes
    password: "{{ pixelflut_user_pwd }}"

- name: Ensure lightdm conf.d exists
  become: True
  file:
    path: "/etc/lightdm/lightdm.conf.d"
    owner: root
    group: root
    state: directory

- name: "Enable autologin for Pixelflut user"
  become: True
  template:
    src: "12-autologin.conf.j2"
    dest: "/etc/lightdm/lightdm.conf.d/12-autologin.conf"
    owner: root
    group: root
    mode: 0644
  notify:
   - Restart lightdm

- name: Upload workaround for window reallocation
  become: True
  become_user: "{{ pixelflut_user }}"
  template:
    src: "relocate_pixelflut.sh.j2"
    dest: "{{ pixelflut_user_home }}/relocate_pixelflut.sh"
  notify:
   - Restart lightdm

- name: Install Pixelflut dependencies
  become: True
  apt:
    pkg: "{{ pixelflut_dependencies }}"
    state: present
    update_cache: yes

- name: Download pixelflut
  become: True
  become_user: "{{ pixelflut_user }}"
  git:
    repo: "{{ pixelflut_repo }}"
    version: "{{ pixelflut_commit }}"
    dest: "{{ pixelflut_dir }}"
  register: pixelflut_checkout

- name: Build Pixelflut on change
  become: True
  become_user: "{{ pixelflut_user }}"
  command: "{{ pixelflut_build_command }}"
  args:
    chdir: "{{ pixelflut_dir }}"
  when: pixelflut_checkout is changed
  notify:
   - Restart lightdm

- name: Copy background image if it is existing
  become: True
  become_user: "{{ pixelflut_user }}"
  copy:
    src: "{{ pixelflut_bg_image }}"
    dest: "{{ pixelflut_user_home }}"
    owner: "{{ pixelflut_user }}"
    group: "{{ pixelflut_user }}"
    mode: 0644

- name: "Enable auto start for Pixelflut"
  become: True
  template:
    src: "xsession.j2"
    dest: "{{ pixelflut_user_home}}/.xsession"
    owner: "{{ pixelflut_user }}"
    group: "{{ pixelflut_user }}"
    mode: 0644
  notify:
   - Restart lightdm

- name: Open relevant ports
  become: True
  ufw:
    proto=tcp
    rule={{ item.policy }}
    port={{ item.port }}
  with_items:
    - { policy: 'allow', port: '22' }
    - { policy: 'allow', port: "{{ pixelflut_port }}" }
  notify:
   - Restart ufw

- name: Disable ufw logging
  become: True
  ufw:
    logging=off

- name: Enable ufw
  become: True
  ufw:
    proto: any
    state: enabled
    policy: deny
    direction: incoming
