---
- name: Restart lightdm
  become: True
  service:
    name: lightdm
    state: restarted

- name: Restart ssh
  become: True
  service:
    name: ssh
    state: restarted

- name: Restart ufw
  become: True
  service:
    name: ufw
    state: restarted
